"""create sync tables

Revision ID: 317b3ac96b72
Revises: 
Create Date: 2026-02-16 13:06:57.875184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317b3ac96b72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_key', sa.String(length=100), nullable=False),
    sa.Column('last_run_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('upserted_rows', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updatet_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_key')
    )
    op.create_table('sync_run_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_key', sa.String(length=100), nullable=False),
    sa.Column('run_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('run_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('upserted_rows', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_run_history')
    op.drop_table('sync_run')
    # ### end Alembic commands ###
