"""increase codigo_unidade length

Revision ID: 3d54548ae465
Revises: 0625d176f5c6
Create Date: 2026-03-19 09:35:39.071415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d54548ae465'
down_revision: Union[str, Sequence[str], None] = '0625d176f5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amparo_legal', 'data_inclusao')
    op.drop_constraint(op.f('fk_compra_amparo_legal'), 'compra', type_='foreignkey')
    op.create_foreign_key(None, 'compra', 'amparo_legal', ['amparo_legal_id'], ['id'])
    op.alter_column('unidade_orgao', 'codigo_unidade',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unidade_orgao', 'codigo_unidade',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_constraint(None, 'compra', type_='foreignkey')
    op.create_foreign_key(op.f('fk_compra_amparo_legal'), 'compra', 'amparo_legal', ['amparo_legal_id'], ['id'], ondelete='SET NULL')
    op.add_column('amparo_legal', sa.Column('data_inclusao', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
