"""create compra and related tables with vector

Revision ID: f4214871e326
Revises: 317b3ac96b72
Create Date: 2026-02-16 20:38:44.772213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'f4214871e326'
down_revision: Union[str, Sequence[str], None] = '317b3ac96b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'orgao_entidade',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('cnpj', sa.CHAR(length=14), nullable=False),
        sa.Column('razao_social', sa.String(length=200), nullable=False),
        sa.Column('poder_id', sa.String(length=10), nullable=True),
        sa.Column('esfera_id', sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cnpj')
    )

    op.create_table(
        'unidade_orgao',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('uf_nome', sa.String(length=50), nullable=True),
        sa.Column('uf_sigla', sa.String(length=2), nullable=True),
        sa.Column('codigo_unidade', sa.String(length=10), nullable=True),
        sa.Column('municipio_nome', sa.String(length=100), nullable=True),
        sa.Column('nome_unidade', sa.String(length=200), nullable=True),
        sa.Column('codigo_ibge', sa.String(length=10), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'compra',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('numero_compra', sa.String(length=50), nullable=False),
        sa.Column('processo', sa.String(length=50), nullable=True),
        sa.Column('objeto_compra', sa.Text(), nullable=True),
        sa.Column('ano_compra', sa.Integer(), nullable=True),
        sa.Column('valor_total_homologado', sa.Float(), nullable=True),
        sa.Column('modalidade_id', sa.Integer(), nullable=True),
        sa.Column('modalidade_nome', sa.String(length=100), nullable=True),
        sa.Column('situacao_compra_id', sa.Integer(), nullable=True),
        sa.Column('situacao_compra_nome', sa.String(length=100), nullable=True),
        sa.Column('usuario_nome', sa.String(length=100), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True),
        sa.Column('vector', Vector(1536), nullable=True),  # <- CORRIGIDO
        sa.Column('orgao_entidade_id', sa.UUID(), nullable=True),
        sa.Column('unidade_orgao_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['orgao_entidade_id'], ['orgao_entidade.id']),
        sa.ForeignKeyConstraint(['unidade_orgao_id'], ['unidade_orgao.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'fontes_orcamentarias',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('codigo', sa.Integer(), nullable=True),
        sa.Column('nome', sa.String(length=100), nullable=True),
        sa.Column('descricao', sa.String(length=255), nullable=True),
        sa.Column('data_inclusao', sa.DateTime(timezone=True), nullable=True),
        sa.Column('compra_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['compra_id'], ['compra.id']),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fontes_orcamentarias')
    op.drop_table('compra')
    op.drop_table('unidade_orgao')
    op.drop_table('orgao_entidade')
    # ### end Alembic commands ###
